---
swagger: "2.0"
info:
  version: "2020-05-10T18:03:20Z"
  title: "api.ningenme.net"
host: "api.ningenme.net"
schemes:
- "https"
paths:
  /hoge:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "health check for api"
  /compro/atcoder/users/{atcoder_id}:
    get:
      parameters:
      - name: "atcoder_id"
        in: "path"
        required: true
        type: "string"
      produces:
      - "application/json"
      responses:
        200:
          description: "atcoder user info"
  /compro/atcoder/users/{atcoder_id}/bingo/{contest_type}:
    get:
      parameters:
      - name: "atcoder_id"
        in: "path"
        required: true
        type: "string"
      - name: "contest_type"
        in: "path"
        required: true
        type: "string"
      produces:
      - "application/json"
      responses:
        200:
          description: "atcoder user bingo info"