server:
  port: 8080
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
logging:
  level:
    org:
      springframework: WARN
    ningenme:
      net:
        api:
          infrastructure:
            mysql:
              mapper: INFO

mybatis:
  configuration:
    map-underscore-to-camel-case: true
net:
  api:
    common:
      domain: ${DOMAIN:ningenme.net}
    security:
      encrypt-secret: ${ENCRYPT_SECRET:mYq3t6w9z$C&F)J@NcQfTjWnZr4u7x!A}
      encrypt-algorithm: ${ENCRYPT_ALGORITHM}
    sqs:
      user-access-key-id: ${SQS_USER_ACCESS_KEY_ID}
      user-secret-access-key: ${SQS_USER_SECRET_ACCESS_KEY}
      url-problem-sqs: ${SQS_URL_PROBLEM_SQS}
