spring:
  datasource:
    ningenme-mysql:
      url: ${NINGENME_MYSQL_URL}/ningenme?enabledTLSProtocols=TLSv1.2
      username: ${NINGENME_MYSQL_MASTER_USER_USERNAME}
      password: ${NINGENME_MYSQL_MASTER_USER_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    comicme-mysql:
      url: ${NINGENME_MYSQL_URL}/comicme?enabledTLSProtocols=TLSv1.2
      username: ${NINGENME_MYSQL_MASTER_USER_USERNAME}
      password: ${NINGENME_MYSQL_MASTER_USER_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    compro-mysql:
      url: ${NINGENME_MYSQL_URL}/compro?enabledTLSProtocols=TLSv1.2
      username: ${NINGENME_MYSQL_MASTER_USER_USERNAME}
      password: ${NINGENME_MYSQL_MASTER_USER_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
net:
  api:
    common:
      domain: ${DOMAIN:ningenme.net}
    security:
      encrypt-secret: ${ENCRYPT_SECRET:mYq3t6w9z$C&F)J@NcQfTjWnZr4u7x!A}
      encrypt-algorithm: ${ENCRYPT_ALGORITHM}
    sqs:
      user-access-key-id: ${SQS_USER_ACCESS_KEY_ID}
      user-secret-access-key: ${SQS_USER_SECRET_ACCESS_KEY}
      url-problem-sqs: ${SQS_URL_PROBLEM_SQS}

