spring:
  datasource:
    ningenme-mysql:
      url: jdbc:mysql://localhost:3306/ningenme
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    comicme-mysql:
      url: jdbc:mysql://localhost:13306/comicme
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    compro-mysql:
      url: jdbc:mysql://localhost:23306/compro
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
net:
  api:
    common:
      domain: ningenme.net
    security:
      encrypt-secret: mYq3t6w9z$C&F)J@NcQfTjWnZr4u7x!A
      encrypt-algorithm: HmacSHA256
    sqs:
      user-access-key-id: hoge
      user-secret-access-key: fuga
      url-problem-sqs: http://localhost:8080
