server:
  port: 8080
spring:
  datasource:
    ningenme-mysql:
      url: jdbc:mysql://localhost:3306/ningenme
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  level:
    org:
      springframework: WARN
    ningenme:
      net:
        api:
          infrastructure:
            mysql:
              mapper: INFO
net:
  api:
    common:
      domain: ningenme.net
    security:
      encrypt-secret: mYq3t6w9z$C&F)J@NcQfTjWnZr4u7x!A
      encrypt-algorithm: HmacSHA256
    sqs:
      user-access-key-id: hoge
      user-secret-access-key: fuga
      url-problem-sqs: http://localhost:8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true

