# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: cd-code-deploy

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition net-api --query taskDefinition > task-definition.json

      - name: Get task version
        run: |
          echo 'TASK_DEFINITON<<EOF' >> $GITHUB_ENV
          cat task-definition.json | grep taskDefinitionArn | awk -F '\"' '{print $4}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo ${{ env.TASK_DEFINITON }}

      - name: Make appspec
        run: |

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: net-api-ecs-service
          cluster: ningenme-cluster
          wait-for-service-stability: true
          codedeploy-appspec: appspec.json
          codedeploy-application: net-api-codedeploy-app
          codedeploy-deployment-group: net-api-deployment-group