# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: cd

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-ecr-push:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ECR_REGISTORY: ${{ secrets.AWS_ECR_REGISTORY }}
      AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: jar build
        run: gradle clean build
      - name: image build
        run: docker build -t ${{ env.AWS_ECR_REGISTORY }}/${{ env.AWS_ECR_REPOSITORY }}:latest .
      - name: aws-credential-setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: image push
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ECR_REGISTORY }}
          docker push ${{ env.AWS_ECR_REGISTORY }}/${{ env.AWS_ECR_REPOSITORY }}:latest

  static-push:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: generate javadoc
        run: gradle javadoc
      - name: test
        run: gradle test
      - name: aws-credential-setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: swagger-sync
        run: |
          aws s3 sync ./swagger ${{ env.AWS_S3_BUCKET }}/net-api/swagger --delete
      - name: javadoc-sync
        run: |
          aws s3 sync ./build/docs/javadoc ${{ env.AWS_S3_BUCKET }}/net-api/javadoc --delete
      - name: test-sync
        run: |
          aws s3 sync ./build/reports/tests/test ${{ env.AWS_S3_BUCKET }}/net-api/test --delete
      - name: jacoco-sync
        run: |
          aws s3 sync ./build/reports/jacoco/test/html ${{ env.AWS_S3_BUCKET }}/net-api/jacoco --delete

  deploy:
    needs: build-and-ecr-push
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition net-api --query taskDefinition > task-definition.json

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: net-api-ecs-service
          cluster: ningenme-cluster
          wait-for-service-stability: true
          codedeploy-appspec: appspec.yaml
          codedeploy-application: net-api-codedeploy-app
          codedeploy-deployment-group: net-api-deployment-group

  application-meta-push:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      NET_API_USERNAME: ${{ secrets.NET_API_USERNAME }}
      NET_API_PASSWORD: ${{ secrets.NET_API_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: application-meta push
        run: |
          token=`curl -X POST -d email=${{ env.NET_API_USERNAME }} -d password=${{ env.NET_API_PASSWORD }} https://api.ningenme.net/v1/login -i | grep MeCookie | awk -F '=|;' '{print $2}'`
          curl -X POST -b "MeCookie=${token}" -H "Content-Type: application/json" https://api.ningenme.net/v1/application-metas/net-api



