# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: ci

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: jar build
        run: gradle clean build
#      - name: image build
#        run: docker build -t ${registory}/{repository}:$GITHUB_SHA

