# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: ci-test

on:
  pull_request:
    branches: [ master ]

jobs:
  assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/github-script@v4.1.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: `${{ github.actor }}`
            });
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: diff
        env:
          TARGET_BRANCH: ${{ github.base_ref }}
        run: |
          git fetch origin ${TARGET_BRANCH}
          diff=`git diff origin/${TARGET_BRANCH} HEAD --name-only --relative= | wc -l`
          echo "IS_DIFFED=${diff}" >> $GITHUB_ENV
      - name: diff-true
        if: env.IS_DIFFED > 0
        run: |
          echo true
      - name: diff-false
        if: env.IS_DIFFED == 0
        run: |
          echo false
      - uses: actions/github-script@v4.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels : ['bug','documentation']
            });
  diff2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: diff
        env:
          TARGET_BRANCH: ${{ github.base_ref }}
        run: |
          git fetch origin ${TARGET_BRANCH}
          diff=`git diff origin/${TARGET_BRANCH} HEAD --name-only --relative= | wc -l`
          echo "IS_DIFFED=${diff}" >> $GITHUB_ENV
      - name: diff-false
        if: env.IS_DIFFED == 0
        run: |
          echo false


  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: gradle clean check
