openapi: 3.0.0
info:
  title: net-api
  description: api created by ningenme
  version: 1.0.0
servers:
  - url: https://api.ningenme.net
paths:
  /v1/healthcheck:
    $ref: './paths/HealthCheck.yaml'
  /v1/blogs/posted-counts:
    $ref: './paths/BlogsPostedCounts.yaml'
